'use strict';function v(f,a,b,d){f.A.pc(f.bb,a,b,d,void 0)}function H(f,a,b,d){f.A.ca?v(f,a,b,d):f.A.hf()._OnMessageFromDOM({type:"event",component:f.bb,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function J(f,a,b){f.A.C(f.bb,a,b)}function K(f,a){for(const [b,d]of a)J(f,b,d)}function L(f){f.Sb||(f.A.Te(f.de),f.Sb=!0)}window.sa=class{constructor(f,a){this.A=f;this.bb=a;this.Sb=!1;this.de=()=>this.Ga()}jd(){}Ga(){}};function N(f){-1!==f.Sa&&(self.clearTimeout(f.Sa),f.Sa=-1)}
window.Ke=class{constructor(f,a){this.Pc=f;this.vg=a;this.Sa=-1;this.Tb=-Infinity;this.ee=()=>{this.Sa=-1;this.Tb=Date.now();this.hb=!0;this.Pc();this.hb=!1};this.Nd=this.hb=!1}c(){N(this);this.ee=this.Pc=null}};"use strict";function O(f,a){J(f,"get-element",b=>{const d=f.ba.get(b.elementId);return a(d,b)})}
window.Qg=class extends self.sa{constructor(f,a){super(f,a);this.ba=new Map;this.Oc=!0;K(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ba.get(b);this.Oc&&d.parentElement.removeChild(d);this.ba.delete(b)}}],["set-visible",b=>{this.Oc&&(this.ba.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Oc){var d=this.ba.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ba.get(b.elementId);throw Error("required override");}],["focus",b=>this.Ic(b)],["set-css-style",b=>{this.ba.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ba.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ba.get(b.elementId).removeAttribute(b.name)}]]);O(this,b=>b)}Ic(f){var a=this.ba.get(f.elementId);f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(m){const c=document.createElement("script");c.async=!1;c.type="module";return m.Gg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=m.Kg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=m;document.head.appendChild(c)})}let d=!1,g=!1;function n(){if(!d){try{new Worker("blob://",{get type(){g=!0}})}catch(m){}d=!0}return g}const q=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let w=new Audio;const B={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus")&&!q,"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;async function D(m){m=
await x(m);return(new TextDecoder("utf-8")).decode(m)}function x(m){return new Promise((c,k)=>{const l=new FileReader;l.onload=p=>c(p.target.result);l.onerror=p=>k(p);l.readAsArrayBuffer(m)})}const y=[];let C=0;window.RealFile=window.File;const E=[],A=new Map,F=new Map;let I=0;const M=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");M.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.fa=class m{constructor(c){this.ca=
c.Mg;this.pa=null;this.F="";this.cc=c.Jg;this.wb={};this.La=this.vb=null;this.Qb=[];this.kb=this.K=this.Qa=null;this.Pa=-1;this.Ag=()=>this.Gf();this.Oa=[];this.s=c.fe;this.ib="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&n()||(this.ca=!1);if("playable-ad"===this.s||"instant-games"===this.s)this.ca=!1;if("cordova"===this.s&&this.ca)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],
10)||(this.ca=!1)}else this.ca=!1;this.Vb=this.ia=null;"html5"!==this.s&&"playable-ad"!==this.s||!this.ib||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.C("runtime","cordova-fetch-local-file",k=>this.qf(k));this.C("runtime","create-job-worker",()=>this.rf());"cordova"===this.s?document.addEventListener("deviceready",()=>this.Ad(c)):this.Ad(c)}c(){this.vc();this.pa&&(this.pa=this.pa.onmessage=
null);this.vb&&(this.vb.terminate(),this.vb=null);this.La&&(this.La.c(),this.La=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}Fe(){return f&&"cordova"===this.s}oc(){const c=navigator.userAgent;return f&&e.has(this.s)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(c)}async Ad(c){"macos-wkwebview"===this.s&&this.Mc({type:"ready"});if("playable-ad"===this.s){this.ia=self.c3_base64files;this.Vb={};await this.Ye();for(let l=0,p=c.Ta.length;l<p;++l){var k=c.Ta[l].toLowerCase();
this.Vb.hasOwnProperty(k)?c.Ta[l]={Gg:!0,Kg:this.Vb[k]}:this.ia.hasOwnProperty(k)&&(c.Ta[l]=URL.createObjectURL(this.ia[k]))}}c.Bg?this.F=c.Bg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Og&&(this.wb=c.Og);k=new MessageChannel;this.pa=k.port1;this.pa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Cf(l));this.kb=new self.Ge(this);await P(this.kb);
"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.kf(c,k.port2):await this.jf(c,k.port2)}yc(c){c=this.wb.hasOwnProperty(c)?this.wb[c]:c.endsWith("/workermain.js")&&this.wb.hasOwnProperty("workermain.js")?this.wb["workermain.js"]:"playable-ad"===this.s&&this.ia.hasOwnProperty(c.toLowerCase())?this.ia[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async ic(c,k,
l){if(c.startsWith("blob:"))return new Worker(c,l);if("cordova"===this.s&&this.ib)return c=await this.xb(l.Fg?c:this.cc+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}xa(){return Math.max(window.innerWidth,1)}wa(){return Math.max(window.innerHeight,1)}zd(c){var k=
this.kb;return{baseUrl:this.F,windowInnerWidth:this.xa(),windowInnerHeight:this.wa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Wa(),projectData:c.Vg,previewImageBlobs:window.cr_previewImageBlobs||this.ia,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Tg||"",exportType:c.fe,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Ug,jobScheduler:{inputPort:k.Vc,outputPort:k.bd,maxNumWorkers:k.xg},supportedAudioFormats:B,
opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cc+"opus.wasm.wasm",isFileProtocol:this.ib,isiOSCordova:this.Fe(),isiOSWebView:this.oc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async kf(c,k){var l=this.yc(c.Ng);this.vb=await this.ic(l,this.F,{type:"module",name:"Runtime",Fg:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);
window.c3canvas=this.K;let p=c.hd||[],u=c.Ta;p=await Promise.all(p.map(r=>this.Ha(r)));u=await Promise.all(u.map(r=>this.Ha(r)));if("cordova"===this.s)for(let r=0,t=c.fc.length;r<t;++r){const z=c.fc[r],G=z[0];if(G===c.fd||"scriptsInEvents.js"===G||G.endsWith("/scriptsInEvents.js"))z[1]=await this.Ha(G)}this.vb.postMessage(Object.assign(this.zd(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:p,engineScripts:u,projectScripts:c.fc,mainProjectScript:c.fd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,l,...Q(this.kb)]);this.Qb=E.map(r=>new r(this));this.yd();self.c3_callFunction=(r,t)=>this.Qa.lf(r,t);"preview"===this.s&&(self.goToLastErrorScript=()=>this.pc("runtime","go-to-last-error-script"))}async jf(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Qb=E.map(r=>new r(this));this.yd();var l=c.Ta.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(c.hd)&&l.unshift(...c.hd);l=await Promise.all(l.map(r=>
this.Ha(r)));await Promise.all(l.map(r=>b(r)));l=self.C3_ProjectScriptsStatus;const p=c.fd,u=c.fc;for(let [r,t]of u)if(t||(t=r),r===p)try{t=await this.Ha(t),await b(t),"preview"!==this.s||l[r]||this.Id(r,"main script did not run to completion")}catch(z){this.Id(r,z)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=await this.Ha(t),await b(t);"preview"===this.s&&"object"!==typeof self.Pg.Rg?(this.Jb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.zd(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:M}),this.Cd(),this.La=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.La,c))}Id(c,k){this.Jb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Cd(){this.Jb()}Jb(){const c=
window.Cg;c&&(c.parentElement.removeChild(c),window.Cg=null)}async rf(){const c=await R(this.kb);return{outputPort:c,transferables:[c]}}hf(){if(this.ca)throw Error("not available in worker mode");return this.La}pc(c,k,l,p,u){this.pa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:null},u)}rd(c,k,l,p,u){const r=I++,t=new Promise((z,G)=>{F.set(r,{resolve:z,reject:G})});this.pa.postMessage({type:"event",component:c,handler:k,dispatchOpts:p||null,data:l,responseId:r},
u);return t}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.wf(c);if("result"===k)this.Jf(c);else if("runtime-ready"===k)this.Kf();else if("alert-error"===k)this.Jb(),alert(c.message);else if("creating-runtime"===k)this.Cd();else throw Error(`unknown message '${k}'`);}wf(c){const k=c.component,l=c.handler,p=c.data,u=c.responseId;if(c=A.get(k))if(c=c.get(l)){var r=null;try{r=c(p)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Ib(u,!1,""+t);return}if(null===
u)return r;r&&r.then?r.then(t=>this.Ib(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Ib(u,!1,""+t)}):this.Ib(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ib(c,k,l){let p;l&&l.transferables&&(p=l.transferables);this.pa.postMessage({type:"result",responseId:c,isOk:k,result:l},p)}Jf(c){const k=c.responseId,l=c.isOk;c=c.result;const p=F.get(k);l?p.resolve(c):p.reject(c);F.delete(k)}C(c,
k,l){let p=A.get(c);p||(p=new Map,A.set(c,p));if(p.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);p.set(k,l)}static Da(c){if(E.includes(c))throw Error("DOM handler already added");E.push(c)}yd(){for(const c of this.Qb)if("runtime"===c.bb){this.Qa=c;return}throw Error("cannot find runtime DOM handler");}Cf(c){this.pc("debugger","message",c)}Kf(){for(const c of this.Qb)c.jd()}static Wa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Kb(c){h=!!c}Te(c){this.Oa.push(c);this.Lc()}Wf(c){c=this.Oa.indexOf(c);if(-1===c)throw Error("invalid callback");this.Oa.splice(c,1);this.Oa.length||this.vc()}Lc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Ag))}vc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}Gf(){this.Pa=-1;for(const c of this.Oa)c();this.Lc()}va(c){this.Qa.va(c)}Fa(c){this.Qa.Fa(c)}Kc(){this.Qa.Kc()}Db(c){this.Qa.Db(c)}Ee(){return!!B["audio/webm; codecs=opus"]}async tg(c){c=await this.rd("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}De(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}qd(c){return!this.De(c)}async Ha(c){return"cordova"===this.s&&(c.startsWith("file:")||this.ib&&this.qd(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.xb(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async qf(c){const k=c.filename;switch(c.as){case "text":return await this.we(k);case "buffer":return await this.xb(k);
default:throw Error("unsupported type");}}md(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,p)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,p)},p)})}async we(c){c=await this.md(c);return await D(c)}wc(){if(y.length&&!(8<=C)){C++;var c=y.shift();this.Ze(c.filename,c.Lg,c.Eg)}}xb(c){return new Promise((k,l)=>{y.push({filename:c,Lg:p=>{C--;this.wc();k(p)},Eg:p=>{C--;this.wc();l(p)}});this.wc()})}async Ze(c,k,l){try{const p=await this.md(c),u=await x(p);
k(u)}catch(p){l(p)}}Mc(c){if("windows-webview2"===this.s)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.s)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async Ye(){const c=[];for(const [k,l]of Object.entries(this.ia))c.push(this.Xe(k,l));await Promise.all(c)}async Xe(c,k){if("object"===typeof k)this.ia[c]=new Blob([k.str],{type:k.type}),this.Vb[c]=k.str;else{let l=await this.ff(k);l||(l=
this.af(k));this.ia[c]=l}}async ff(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}af(c){c=this.Qf(c);return this.We(c.data,c.Hg)}Qf(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);k=c.substring(5,k).split(";");c=k[0]||"";
const p=k[2];l="base64"===k[1]||"base64"===p?atob(l):decodeURIComponent(l);return{Hg:c,data:l}}We(c,k){var l=c.length;let p=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,p),t,z;for(z=t=0;t<p;++t)r[t]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=3;l--;)u[z]=c.charCodeAt(z),++z;return new Blob([u],{type:k})}}}"use strict";
{const f=self.fa;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(e){return new Promise((h,m)=>{const c=document.createElement("link");c.onload=()=>h(c);c.onerror=k=>m(k);c.rel=
"stylesheet";c.href=e;document.head.appendChild(c)})}function w(e){return new Promise((h,m)=>{const c=new Image;c.onload=()=>h(c);c.onerror=k=>m(k);c.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await w(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((h,m)=>{let c=new FileReader;c.onload=k=>h(k.target.result);c.onerror=k=>m(k);c.readAsText(e)})}async function x(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var c=await D(e);c=(new DOMParser).parseFromString(c,
"image/svg+xml");const k=c.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),p=k.getAttribute("height");if(!l.includes("%")&&!p.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");c=(new XMLSerializer).serializeToString(c);e=new Blob([c],{type:"image/svg+xml"});return await B(e)}function y(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),E=new Set(["canvas","body","html"]);function A(e){E.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function F(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,c,k){e=await x(e,h,m);const l=document.createElement("canvas");l.width=c;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function M(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Da(class extends self.sa{constructor(e){super(e,"runtime");this.Sd=!0;this.Ra=-1;this.dd="any";this.Jd=this.Kd=!1;this.Yc=
this.sb=this.za=null;e.C("canvas","update-size",c=>this.Nf(c));e.C("runtime","invoke-download",c=>this.Af(c));e.C("runtime","raster-svg-image",c=>this.Hf(c));e.C("runtime","get-svg-image-size",c=>this.yf(c));e.C("runtime","set-target-orientation",c=>this.Lf(c));e.C("runtime","register-sw",()=>this.If());e.C("runtime","post-to-debugger",c=>this.Ed(c));e.C("runtime","go-to-script",c=>this.Ed(c));e.C("runtime","before-start-ticking",()=>this.pf());e.C("runtime","debug-highlight",c=>this.sf(c));e.C("runtime",
"enable-device-orientation",()=>this.Ve());e.C("runtime","enable-device-motion",()=>this.Ue());e.C("runtime","add-stylesheet",c=>this.nf(c));e.C("runtime","alert",c=>this.Cc(c));e.C("runtime","hide-cordova-splash",()=>this.zf());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const k=c.target;h.has(k.tagName.toLowerCase())||y(k)||c.preventDefault()});const m=e.K;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",
A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.pb=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",F,{passive:!1});window.addEventListener("wheel",F,{passive:!1});window.addEventListener("resize",()=>this.Of());window.addEventListener("fullscreenchange",
()=>this.Ya());window.addEventListener("webkitfullscreenchange",()=>this.Ya());window.addEventListener("mozfullscreenchange",()=>this.Ya());window.addEventListener("fullscreenerror",c=>this.Ec(c));window.addEventListener("webkitfullscreenerror",c=>this.Ec(c));window.addEventListener("mozfullscreenerror",c=>this.Ec(c));e.oc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var c=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?k.has(l.type.toLowerCase()||"text"):y(l)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>this.Pf(c);this.Ma=new Set;this.Wb=new WeakSet;this.oa=!1}pf(){"cordova"===this.A.s?(document.addEventListener("pause",()=>this.Jc(!0)),document.addEventListener("resume",()=>this.Jc(!1))):document.addEventListener("visibilitychange",()=>this.Jc(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}jd(){window.addEventListener("focus",()=>
this.$a("window-focus"));window.addEventListener("blur",()=>{this.$a("window-blur",{parentHasFocus:M()});this.pb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||y(h))&&this.$a("keyboard-blur")});window.addEventListener("keydown",h=>this.Dd("keydown",h));window.addEventListener("keyup",h=>this.Dd("keyup",h));window.addEventListener("dblclick",h=>this.Gc("dblclick",h,d));window.addEventListener("wheel",h=>this.Ef(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.zc(h);this.Za("pointerdown",h)}),this.A.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.sb=new self.Ke(()=>this.df(),5),this.sb.Nd=!0,window.addEventListener("pointerrawupdate",h=>this.Ff(h))):window.addEventListener("pointermove",h=>this.Za("pointermove",h)),window.addEventListener("pointerup",h=>this.Za("pointerup",h)),window.addEventListener("pointercancel",h=>this.Za("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.zc(h);this.Hc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Hc("pointermove",h)),window.addEventListener("mouseup",h=>this.Hc("pointerup",h)),window.addEventListener("touchstart",h=>{this.zc(h);this.Hb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Hb("pointermove",h)),window.addEventListener("touchend",h=>this.Hb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Hb("pointercancel",h)));const e=()=>this.Kc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}$a(e,h){v(this,e,h||null,n)}xa(){return this.A.xa()}wa(){return this.A.wa()}Of(){const e=this.xa(),h=this.wa();this.$a("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()});this.A.oc()&&(-1!==this.Ra&&clearTimeout(this.Ra),this.Fd(e,h,0))}Xf(e,h,m){-1!==this.Ra&&clearTimeout(this.Ra);this.Ra=setTimeout(()=>this.Fd(e,
h,m),48)}Fd(e,h,m){const c=this.xa(),k=this.wa();this.Ra=-1;c!=e||k!=h?this.$a("window-resize",{innerWidth:c,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Wa()}):10>m&&this.Xf(c,k,m+1)}Lf(e){this.dd=e.targetOrientation}pg(){const e=this.dd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Ya(){const e=f.Wa();e&&"any"!==this.dd&&this.pg();v(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.xa(),innerHeight:this.wa()})}Ec(e){console.warn("[Construct 3] Fullscreen request failed: ",e);v(this,"fullscreenerror",
{isFullscreen:f.Wa(),innerWidth:this.xa(),innerHeight:this.wa()})}Jc(e){e?this.A.vc():this.A.Lc();v(this,"visibilitychange",{hidden:e})}Dd(e,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;H(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Ef(e){v(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},d)}Gc(e,h,m){a(h)||H(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},m)}Hc(e,h){if(!a(h)){var m=this.pb;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");H(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.pb=h.buttons;this.Gc(h.type,h,g)}}Za(e,h){if(this.sb&&"pointermove"!==e){var m=this.sb;m.hb||(N(m),m.Tb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.pb);H(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Gc(m,h,g),this.pb=h.buttons)}Ff(e){this.Yc=e;e=this.sb;if(-1===e.Sa){var h=Date.now(),m=h-e.Tb,c=e.vg;m>=c&&e.Nd?(e.Tb=h,e.hb=!0,e.Pc(),e.hb=!1):e.Sa=self.setTimeout(e.ee,Math.max(c-m,4))}}df(){this.Za("pointermove",this.Yc);this.Yc=null}Hb(e,h){for(let m=0,c=h.changedTouches.length;m<c;++m){const k=h.changedTouches[m];H(this,e,{pointerId:k.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},d)}}zc(e){window!==window.top&&window.focus();this.Bd(e.target)&&document.activeElement&&!this.Bd(document.activeElement)&&document.activeElement.blur()}Bd(e){return!e||e===document||
e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Ve(){this.Kd||(this.Kd=!0,window.addEventListener("deviceorientation",e=>this.uf(e)),window.addEventListener("deviceorientationabsolute",e=>this.vf(e)))}Ue(){this.Jd||(this.Jd=!0,window.addEventListener("devicemotion",e=>this.tf(e)))}uf(e){v(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},
d)}vf(e){v(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}tf(e){let h=null;var m=e.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var c=e.accelerationIncludingGravity;c&&(m={x:c.x||0,y:c.y||0,z:c.z||0});c=null;const k=e.rotationRate;k&&(c={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});v(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:c,interval:e.interval,timeStamp:e.timeStamp},
d)}Nf(e){const h=this.A.K;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Sd&&(h.style.display="",this.Sd=!1)}Af(e){const h=e.url;e=e.filename;const m=document.createElement("a"),c=document.body;m.textContent=e;m.href=h;m.download=e;c.appendChild(m);m.click();c.removeChild(m)}async Hf(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);
h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async yf(e){return await self.C3_GetSvgImageSize(e.blob)}async nf(e){await q(e.url)}Kc(){var e=[...this.Ma];this.Ma.clear();if(!this.oa)for(const h of e)(e=h.play())&&e.catch(()=>{this.Wb.has(h)||this.Ma.add(h)})}va(e){if("function"!==typeof e.play)throw Error("missing play function");this.Wb.delete(e);let h;try{h=e.play()}catch(m){this.Ma.add(e);return}h&&h.catch(()=>{this.Wb.has(e)||this.Ma.add(e)})}Fa(e){this.Ma.delete(e);
this.Wb.add(e)}Db(e){this.oa=!!e}zf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}sf(e){if(e.show){this.za||(this.za=document.createElement("div"),this.za.id="inspectOutline",document.body.appendChild(this.za));var h=this.za;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.za&&(this.za.style.display="none")}If(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ed(e){window.c3_postToMessagePort&&
(e.from="runtime",window.c3_postToMessagePort(e))}lf(e,h){return this.A.rd(this.bb,"js-invoke-function",{name:e,params:h},void 0,void 0)}Cc(e){alert(e.message)}Pf(e){"entered-fullscreen"===e?(f.Kb(!0),this.Ya()):"exited-fullscreen"===e?(f.Kb(!1),this.Ya()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function P(f){if(f.ug)throw Error("already initialised");f.ug=!0;var a=f.bc.yc("dispatchworker.js");f.Rc=await f.bc.ic(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.Vc=a.port1;f.Rc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.bd=await R(f)}function Q(f){return[f.Vc,f.bd]}
async function R(f){const a=f.Td.length;var b=f.bc.yc("jobworker.js");b=await f.bc.ic(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;f.Rc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);f.Td.push(b);return g.port1}
self.Ge=class{constructor(f){this.bc=f;this.F=f.F;this.F="preview"===f.s?this.F+"workers/":this.F+f.cc;this.xg=Math.min(navigator.hardwareConcurrency||2,16);this.Rc=null;this.Td=[];this.bd=this.Vc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.fa({Mg:!1,Ng:"workermain.js",Ta:["scripts/c3runtime.js"],fc:[],fd:"",Jg:"scripts/",hd:[],fe:"html5"}));"use strict";
async function S(f,a){a=a.type;let b=!0;0===a?b=await T():1===a&&(b=await U());v(f,"permission-result",{type:a,result:b})}async function T(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function U(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.fa.Da(class extends self.sa{constructor(f){super(f,"touch");J(this,"request-permission",a=>S(this,a))}});"use strict";self.fa.Da(class extends self.sa{constructor(f){super(f,"mouse");J(this,"cursor",a=>{document.documentElement.style.cursor=a})}});
"use strict";
{const f=180/Math.PI;self.da=class extends self.sa{constructor(a){super(a,"audio");this.Pb=this.f=null;this.Rb=this.Uc=!1;this.ra=()=>this.qg();this.$=[];this.D=[];this.ha=null;this.Ud="";this.Vd=-1;this.rb=new Map;this.Zc=1;this.oa=!1;this.ed=0;this.dc=1;this.Sc=0;this.Xd="HRTF";this.Od="inverse";this.Yd=600;this.Wd=1E4;this.$d=1;this.Qd=this.cd=!1;this.ce=this.A.Ee();this.aa=new Map;this.Ja=new Set;this.Wc=!1;this.$c="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Df(b,d);this.Ob=null;
self.C3Audio_GetOutputStream=()=>this.xf();self.C3Audio_DOMInterface=this;K(this,[["create-audio-context",b=>this.$e(b)],["play",b=>this.Rf(b)],["stop",b=>this.ng(b)],["stop-all",()=>this.og()],["set-paused",b=>this.gg(b)],["set-volume",b=>this.lg(b)],["fade-volume",b=>this.ef(b)],["set-master-volume",b=>this.eg(b)],["set-muted",b=>this.fg(b)],["set-silent",b=>this.ig(b)],["set-looping",b=>this.dg(b)],["set-playback-rate",b=>this.hg(b)],["seek",b=>this.Yf(b)],["preload",b=>this.Sf(b)],["unload",b=>
this.rg(b)],["unload-all",()=>this.sg()],["set-suspended",b=>this.jg(b)],["add-effect",b=>this.wd(b)],["set-effect-param",b=>this.ag(b)],["remove-effects",b=>this.Uf(b)],["tick",b=>this.Mf(b)],["load-state",b=>this.Bf(b)]])}async $e(a){a.isiOSCordova&&(this.cd=!0);this.ed=a.timeScaleMode;this.Xd=["equalpower","HRTF","soundfield"][a.panningModel];this.Od=["linear","inverse","exponential"][a.distanceModel];this.Yd=a.refDistance;this.Wd=a.maxDistance;this.$d=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ce||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.xd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.xd()};this.Pb=this.f.createGain();this.Pb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.jc();try{await Promise.all(a.preloadList.map(d=>this.Fb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}xd(){this.Rb||(this.Uc=!1,window.addEventListener("pointerup",this.ra,!0),window.addEventListener("touchend",this.ra,!0),window.addEventListener("click",this.ra,!0),window.addEventListener("keydown",this.ra,!0),this.Rb=!0)}bf(){this.Rb&&(this.Uc=!0,window.removeEventListener("pointerup",this.ra,!0),window.removeEventListener("touchend",
this.ra,!0),window.removeEventListener("click",this.ra,!0),window.removeEventListener("keydown",this.ra,!0),this.Rb=!1)}qg(){if(!this.Uc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.bf()}}W(){return this.f}jc(){return this.f.currentTime}ta(){return this.Pb}od(a){return(a=this.aa.get(a.toLowerCase()))?a[0].P():this.ta()}ge(a,b){a=a.toLowerCase();let d=this.aa.get(a);
d||(d=[],this.aa.set(a,d));b.cg(d.length);b.kg(a);d.push(b);this.Hd(a)}Hd(a){let b=this.ta();const d=this.aa.get(a);if(d&&d.length){b=d[0].P();for(let g=0,n=d.length;g<n;++g){const q=d[g];g+1===n?q.S(this.ta()):q.S(d[g+1].P())}}for(const g of this.ma(a))g.Le(b);this.Aa&&this.$c===a&&(this.Aa.disconnect(),this.Aa.connect(b))}zb(){return this.Zc}Ab(){return this.oa}bg(){this.Qd=!0}ye(a,b){return b?this.A.tg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):
new Promise((d,g)=>{this.f.decodeAudioData(a,d,g)})}va(a){this.A.va(a)}Fa(a){this.A.Fa(a)}sd(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const n=this.D[d];this.D[b]=n;n.L===a?n.c():++b}this.D.length=b}Me(){let a=0;for(let b=0,d=this.$.length;b<d;++b){const g=this.$[b];this.$[a]=g;g.ua()?g.c():++a}this.$.length=a}*ma(a){if(a)for(const b of this.D)self.da.ze(b.Y,a)&&(yield b);else this.ha&&!this.ha.T()&&(yield this.ha)}async Fb(a,b,d,g,n){for(const q of this.$)if(q.Va()===b)return await V(q),q;
if(n)return null;g&&(this.cd||this.Qd)&&this.Me();n="audio/webm; codecs=opus"===d&&!this.ce;g&&n&&this.bg();a=!g||this.cd||n?new self.ue(this,a,b,d,g,n):new self.se(this,a,b,d,g);this.$.push(a);await V(a);return a}async xc(a,b,d,g,n){for(const q of this.D)if(q.Va()===b&&(q.hc()||n))return q.Oe(g),q;a=await this.Fb(a,b,d,n);g="html5"===a.Nc?new self.te(a.i,a,g):new self.ve(a.i,a,g);this.D.push(g);return g}Se(a){let b=this.rb.get(a);if(!b){let d=null;b={gd:0,Ig:new Promise(g=>d=g),resolve:d};this.rb.set(a,
b)}b.gd++}Vf(a){const b=this.rb.get(a);if(!b)throw Error("expected pending tag");b.gd--;0===b.gd&&(b.resolve(),this.rb.delete(a))}uc(a){a||(a=this.Ud);return(a=this.rb.get(a))?a.Ig:Promise.resolve()}Gb(){if(0<this.Ja.size)L(this);else for(const a of this.D)if(a.pd()){L(this);break}}Ga(){for(var a of this.Ja)a.Ga();a=this.jc();for(var b of this.D)b.Ga(a);b=this.D.filter(d=>d.pd()).map(d=>d.Ua());v(this,"state",{tickCount:this.Vd,audioInstances:b,analysers:[...this.Ja].map(d=>d.Be())});0===b.length&&
0===this.Ja.size&&this.Sb&&(this.A.Wf(this.de),this.Sb=!1)}qc(a,b,d){v(this,"trigger",{type:a,tag:b,aiid:d})}async Rf(a){const b=a.originalUrl,d=a.url,g=a.type,n=a.isMusic,q=a.tag,w=a.isLooping,B=a.vol,D=a.pos,x=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.f.currentTime);this.Ud=q;this.Se(q);try{this.ha=await this.xc(b,d,g,q,n),x?(this.ha.Cb(!0),this.ha.Ne(x.x,x.y,x.angle,
x.innerAngle,x.outerAngle,x.outerGain),x.hasOwnProperty("uid")&&this.ha.Pe(x.uid)):this.ha.Cb(!1),this.ha.Play(w,B,D,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Vf(q)}L(this)}ng(a){a=a.tag;for(const b of this.ma(a))b.na()}og(){for(const a of this.D)a.na()}gg(a){const b=a.tag;a=a.paused;for(const d of this.ma(b))a?d.Xa():d.Bb();this.Gb()}lg(a){const b=a.tag;a=a.vol;for(const d of this.ma(b))d.Eb(a)}async ef(a){const b=a.tag,d=a.vol,g=a.duration;
a=a.stopOnEnd;await this.uc(b);for(const n of this.ma(b))n.Ae(d,g,a);this.Gb()}eg(a){this.Zc=a.vol;for(const b of this.D)b.Mb()}fg(a){const b=a.tag;a=a.isMuted;for(const d of this.ma(b))d.td(a)}ig(a){this.oa=a.isSilent;this.A.Db(this.oa);for(const b of this.D)b.Lb()}dg(a){const b=a.tag;a=a.isLooping;for(const d of this.ma(b))d.sc(a)}async hg(a){const b=a.tag;a=a.rate;await this.uc(b);for(const d of this.ma(b))d.vd(a)}async Yf(a){const b=a.tag;a=a.pos;await this.uc(b);for(const d of this.ma(b))d.rc(a)}async Sf(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.xc(b,d,g,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async rg(a){if(a=await this.Fb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.$.indexOf(a),-1!==a&&this.$.splice(a,1)}sg(){for(const a of this.$)a.c();this.$.length=0}jg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.tc(a);a&&this.f.suspend&&this.f.suspend()}Mf(a){this.dc=a.timeScale;this.Sc=a.gameTime;this.Vd=a.tickCount;if(0!==this.ed)for(var b of this.D)b.Ia();
(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.ga===a&&g.ud(d.x,d.y,d.angle)}}async wd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.me(this,...g);else if("delay"===b)g=new self.ke(this,...g);else if("convolution"===b){b=null;try{b=await this.Fb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",n);return}g=new self.je(this,b.Z,
...g);g.Zf(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.ne(this,...g);else if("phaser"===b)g=new self.pe(this,...g);else if("gain"===b)g=new self.oe(this,...g);else if("tremolo"===b)g=new self.re(this,...g);else if("ringmod"===b)g=new self.qe(this,...g);else if("distortion"===b)g=new self.le(this,...g);else if("compressor"===b)g=new self.ie(this,...g);else if("analyser"===b)g=new self.he(this,...g);else throw Error("invalid effect type");this.ge(d,g);this.Gd()}ag(a){const b=
a.index,d=a.param,g=a.value,n=a.ramp,q=a.time;a=this.aa.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,n,q),this.Gd())}Uf(a){a=a.tag.toLowerCase();const b=this.aa.get(a);if(b&&b.length){for(const d of b)d.c();this.aa.delete(a);this.Hd(a)}}Re(a){this.Ja.add(a);this.Gb()}Tf(a){this.Ja.delete(a)}Gd(){this.Wc||(this.Wc=!0,Promise.resolve().then(()=>this.cf()))}cf(){const a={};for(const [b,d]of this.aa)a[b]=d.map(g=>g.Ua());v(this,"fxstate",{fxstate:a});this.Wc=!1}async Bf(a){const b=a.saveLoadMode;if(3!==
b)for(var d of this.D)d.ua()&&1===b||(d.ua()||2!==b)&&d.na();for(const g of this.aa.values())for(const n of g)n.c();this.aa.clear();this.dc=a.timeScale;this.Sc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.oa=a.isSilent;this.A.Db(this.oa);this.Zc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(n=>this.wd(n))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.mf(g,b)));this.Gb()}async mf(a,b){if(3!==b){var d=a.bufferOriginalUrl,
g=a.bufferUrl,n=a.bufferType,q=a.isMusic,w=a.tag,B=a.isLooping,D=a.volume,x=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.xc(d,g,n,w,q)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.Je(a.pan);b.Play(B,D,x,0);a.isPlaying||b.Xa();b.Bc(a)}}}Df(a,b){this.Aa&&this.Aa.disconnect();this.$c=b.toLowerCase();this.Aa=this.f.createMediaStreamSource(a);this.Aa.connect(this.od(this.$c))}xf(){this.Ob||(this.Ob=this.f.createMediaStreamDestination(),this.Pb.connect(this.Ob));
return this.Ob.stream}static ze(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Qe(a){return a*f}static xe(a){return Math.pow(10,a/20)}static nd(a){return Math.max(Math.min(self.da.xe(a),1),0)}static Ie(a){return Math.log(a)/Math.log(10)*20}static He(a){return self.da.Ie(Math.max(Math.min(a,1),0))}static Dg(a,b){return 1-Math.exp(-b*a)}};self.fa.Da(self.da)}"use strict";function V(f){f.Ub||(f.Ub=f.Ac());return f.Ub}
self.kd=class{constructor(f,a,b,d,g){this.i=f;this.zg=a;this.Ca=b;this.R=d;this.wg=g;this.Nc="";this.Ub=null}c(){this.Ub=this.i=null}Ac(){}W(){return this.i.W()}lc(){return this.zg}Va(){return this.Ca}kc(){return this.R}ua(){return this.wg}ea(){}};"use strict";
self.se=class extends self.kd{constructor(f,a,b,d,g){super(f,a,b,d,g);this.Nc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.lb=this.mb=null;this.J.addEventListener("canplaythrough",()=>!0);this.qb=this.W().createGain();this.ob=null;this.J.addEventListener("canplay",()=>{this.mb&&(this.mb(),this.lb=this.mb=null);!this.ob&&this.J&&(this.ob=this.W().createMediaElementSource(this.J),this.ob.connect(this.qb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Ca}' error: `,n);this.lb&&(this.lb(n),this.lb=this.mb=null)})}c(){this.i.sd(this);this.qb.disconnect();this.qb=null;this.ob.disconnect();this.ob=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Ac(){return new Promise((f,a)=>{this.mb=f;this.lb=a;this.J.src=this.Ca})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function W(f){if(f.ya)return f.ya;var a=f.i.A;if("cordova"===a.s&&a.qd(f.Ca)&&a.ib)f.ya=await a.xb(f.Ca);else{a=await fetch(f.Ca);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.ya=await a.arrayBuffer()}}async function X(f){if(f.Z)return f.Z;f.Z=await f.i.ye(f.ya,f.yg);f.ya=null}
self.ue=class extends self.kd{constructor(f,a,b,d,g,n){super(f,a,b,d,g);this.Nc="webaudio";this.Z=this.ya=null;this.yg=!!n}c(){this.i.sd(this);this.Z=this.ya=null;super.c()}async Ac(){try{await W(this),await X(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Ca}': `,f)}}ea(){return this.Z?this.Z.duration:0}};"use strict";
{let f=0;self.ld=class{constructor(a,b,d){this.i=a;this.L=b;this.Y=d;this.Nb=f++;this.M=this.W().createGain();this.M.connect(this.ta());this.B=null;this.jb=!1;this.ka=[0,0,0];this.ja=[0,0,0];this.H=!0;this.V=this.la=this.G=!1;this.ub=1;this.Ka=!1;this.qa=1;a=this.i.ed;this.Xc=1===a&&!this.ua()||2===a;this.fb=this.ga=-1;this.be=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ta(){return this.i.od(this.Y)}zb(){return this.i.zb()}yb(){return this.Xc?
this.i.Sc:performance.now()/1E3}lc(){return this.L.lc()}Va(){return this.L.Va()}kc(){return this.L.kc()}ua(){return this.L.ua()}Oe(a){this.Y=a}T(){}hc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}pd(){return!this.H&&!this.T()}Ea(){}ea(){return this.L.ea()}Play(){}na(){}Xa(){}Bb(){}Eb(a){this.ub=a;this.M.gain.cancelScheduledValues(0);this.fb=-1;this.M.gain.value=this.mc()}Ae(a,b,d){if(!this.Ka){a*=this.zb();var g=this.M.gain;g.cancelScheduledValues(0);var n=this.i.jc();b=n+b;g.setValueAtTime(g.value,
n);g.linearRampToValueAtTime(a,b);this.ub=a;this.fb=b;this.be=d}}Mb(){this.Eb(this.ub)}Ga(a){-1!==this.fb&&a>=this.fb&&(this.fb=-1,this.be&&this.na(),this.i.qc("fade-ended",this.Y,this.Nb))}mc(){const a=this.ub*this.zb();return isFinite(a)?a:0}td(a){a=!!a;this.Ka!==a&&(this.Ka=a,this.Lb())}Ab(){return this.i.Ab()}Lb(){}sc(){}vd(a){this.qa!==a&&(this.qa=a,this.Ia())}Ia(){}rc(){}tc(){}Cb(a){a=!!a;this.jb!==a&&((this.jb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Xd,this.B.distanceModel=
this.i.Od,this.B.refDistance=this.i.Yd,this.B.maxDistance=this.i.Wd,this.B.rolloffFactor=this.i.$d),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ta())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ta())))}Ne(a,b,d,g,n,q){this.jb&&(this.ud(a,b,d),a=self.da.Qe,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=q)}ud(a,b,d){this.jb&&(this.ka[0]=a,this.ka[1]=b,this.ka[2]=0,this.ja[0]=Math.cos(d),this.ja[1]=Math.sin(d),this.ja[2]=0,this.B.setPosition(...this.ka),
this.B.setOrientation(...this.ja))}Pe(a){this.ga=a}nc(){}Le(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Nb,tag:this.Y,duration:this.ea(),volume:this.ub,isPlaying:this.IsPlaying(),playbackTime:this.Ea(),playbackRate:this.qa,uid:this.ga,bufferOriginalUrl:this.lc(),bufferUrl:"",bufferType:this.kc(),isMusic:this.ua(),isLooping:this.V,isMuted:this.Ka,resumePosition:this.nc(),pan:this.Ce()}}Bc(a){this.vd(a.playbackRate);this.td(a.isMuted)}Ce(){if(!this.B)return null;const a=
this.B;return{pos:this.ka,orient:this.ja,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ga}}Je(a){if(a){this.Cb(!0);a=this.B;var b=a.pos;this.ka[0]=b[0];this.ka[1]=b[1];this.ka[2]=b[2];b=a.orient;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];a.setPosition(...this.ka);a.setOrientation(...this.ja);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ga=a.uid}else this.Cb(!1)}}}"use strict";
self.te=class extends self.ld{constructor(f,a,b){super(f,a,b);this.L.qb.connect(this.M);this.L.onended=()=>this.Dc()}c(){this.na();this.L.qb.disconnect();super.c()}O(){return this.L.O()}Dc(){this.H=!0;this.ga=-1;this.i.qc("ended",this.Y,this.Nb)}T(){return this.O().ended}hc(){return this.H?!0:this.T()}Ea(){let f=this.O().currentTime;this.V||(f=Math.min(f,this.ea()));return f}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Eb(a);d.muted&&(d.muted=!1);
if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,g)}this.i.va(d);this.G=this.H=!1;this.V=f;this.qa=1}na(){const f=this.O();f.paused||f.pause();this.i.Fa(f);this.H=!0;this.G=!1;this.ga=-1}Xa(){if(!(this.G||this.H||this.T())){var f=this.O();f.paused||f.pause();this.i.Fa(f);this.G=!0}}Bb(){!this.G||this.H||this.T()||(this.i.va(this.O()),this.G=!1)}Lb(){this.O().muted=this.Ka||this.Ab()}sc(f){f=!!f;this.V!==f&&
(this.V=f,this.O().loop=f)}Ia(){let f=this.qa;this.Xc&&(f*=this.i.dc);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}rc(f){if(!this.H&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}nc(){return this.Ea()}tc(f){f?this.IsPlaying()?(this.O().pause(),this.la=!0):this.la=!1:this.la&&(this.i.va(this.O()),this.la=!1)}};"use strict";
function Y(f){f.j&&f.j.disconnect();f.j=null;f.ab=null}
self.ve=class extends self.ld{constructor(f,a,b){super(f,a,b);this.j=null;this.Xb=d=>this.Dc(d);this.Tc=!0;this.ab=null;this.N=this.Yb=this.Zb=0;this.ad=1}c(){this.na();Y(this);this.Xb=null;super.c()}Dc(f){this.G||this.la||f.target!==this.ab||(this.H=this.Tc=!0,this.ga=-1,Y(this),this.i.qc("ended",this.Y,this.Nb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Tc}hc(){return!this.j||this.H?!0:this.T()}Ea(){let f;f=this.G?this.N:this.Yb+(this.yb()-this.Zb)*this.qa;this.V||(f=Math.min(f,this.ea()));
return f}Play(f,a,b,d){this.ad=1;this.Eb(a);Y(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.Z;this.j.connect(this.M);this.ab=this.j;this.j.onended=this.Xb;this.j.loop=f;this.j.start(d,b);this.G=this.H=this.Tc=!1;this.V=f;this.qa=1;this.Zb=this.yb();this.Yb=b}na(){if(this.j)try{this.j.stop(0)}catch(f){}this.H=!0;this.G=!1;this.ga=-1}Xa(){this.G||this.H||this.T()||(this.N=this.Ea(),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}Bb(){!this.G||this.H||this.T()||(Y(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Mb(),this.Ia(),this.j.start(0,this.N),this.Zb=this.yb(),this.Yb=this.N,this.G=!1)}mc(){return super.mc()*this.ad}Lb(){this.ad=this.Ka||this.Ab()?0:1;this.Mb()}sc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Ia(){let f=this.qa;this.Xc&&(f*=this.i.dc);this.j&&(this.j.playbackRate.value=f)}rc(f){this.H||this.T()||(this.G?this.N=f:(this.Xa(),this.N=f,this.Bb()))}nc(){return this.N}tc(f){f?
this.IsPlaying()?(this.la=!0,this.N=this.Ea(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.la=!1:this.la&&(Y(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.Z,this.j.connect(this.M),this.ab=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Mb(),this.Ia(),this.j.start(0,this.N),this.Zb=this.yb(),this.Yb=this.N,this.la=!1)}Bc(f){super.Bc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Rd=-1;this.R=this.Y="";this.g=null}c(){this.f=null}cg(a){this.Rd=a}kg(a){this.Y=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var n=this.f.currentTime;g+=n;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,g)}}}Ua(){return{type:this.R,tag:this.Y,params:this.g}}}
self.me=class extends f{constructor(a,b,d,g,n,q,w){super(a);this.R="filter";this.g=[b,d,g,n,q,w];this.l=this.o();this.b=this.o();this.b.gain.value=w;this.a=this.o();this.a.gain.value=1-w;this.v=this.f.createBiquadFilter();this.v.type=b;this.v.frequency.value=d;this.v.detune.value=g;this.v.Q.value=n;this.v.gain.vlaue=q;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b)}c(){this.l.disconnect();this.v.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.v.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.v.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.v.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.v.gain,b,d,g)}}};self.ke=class extends f{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.nb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.eb=this.o();this.eb.gain.value=d;this.l.connect(this.nb);this.l.connect(this.a);this.nb.connect(this.b);this.nb.connect(this.U);this.U.connect(this.eb);this.eb.connect(this.nb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.nb.disconnect();this.U.disconnect();this.eb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const n=self.da.nd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=n(b);this.m(this.eb.gain,n(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.je=class extends f{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Md=this.Ld="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.cb=this.f.createConvolver();this.cb.normalize=d;this.cb.buffer=b;this.l.connect(this.cb);this.l.connect(this.a);this.cb.connect(this.b)}c(){this.l.disconnect();this.cb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}Zf(a,b){this.Ld=a;this.Md=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Ld;a.bufferUrl="";a.bufferType=this.Md;return a}};self.ne=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="flanger";this.g=[b,d,g,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.gb=this.o();this.gb.gain.value=n;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.u=this.f.createOscillator();this.u.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.gb);this.gb.connect(this.U);this.u.connect(this.I);this.I.connect(this.U.delayTime);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.U.disconnect();this.u.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.gb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.u.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.gb.gain,b/100,d,g)}}};self.pe=class extends f{constructor(a,b,d,g,n,q,w){super(a);this.R="phaser";this.g=[b,d,g,n,q,w];this.l=this.o();this.a=this.o();this.a.gain.value=1-w/2;this.b=this.o();this.b.gain.value=w/2;this.v=this.f.createBiquadFilter();this.v.type="allpass";this.v.frequency.value=b;this.v.detune.value=
d;this.v.Q.value=g;this.u=this.f.createOscillator();this.u.frequency.value=q;this.I=this.o();this.I.gain.value=n;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b);this.u.connect(this.I);this.I.connect(this.v.frequency);this.u.start(0)}c(){this.u.stop(0);this.l.disconnect();this.v.disconnect();this.u.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.v.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.v.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.v.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.u.frequency,b,d,g)}}};self.oe=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const n=self.da.nd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,g)}}};self.re=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.u=this.f.createOscillator();this.u.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.u.connect(this.I);this.I.connect(this.h.gain);this.u.start(0)}c(){this.u.stop(0);this.u.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,g)}}};self.qe=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.tb=this.o();this.tb.gain.value=
0;this.u=this.f.createOscillator();this.u.frequency.value=b;this.u.connect(this.tb.gain);this.u.start(0);this.l.connect(this.tb);this.l.connect(this.a);this.tb.connect(this.b)}c(){this.u.stop(0);this.u.disconnect();this.tb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.u.frequency,b,d,g)}}};self.le=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="distortion";this.g=[b,d,g,n,q];this.l=this.o();this.ac=this.o();this.$b=this.o();this.$f(g,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.ec=this.f.createWaveShaper();this.Qc=new Float32Array(65536);this.gf(b,d);this.ec.curve=this.Qc;this.l.connect(this.ac);this.l.connect(this.a);this.ac.connect(this.ec);this.ec.connect(this.$b);
this.$b.connect(this.b)}c(){this.l.disconnect();this.ac.disconnect();this.ec.disconnect();this.$b.disconnect();this.b.disconnect();this.a.disconnect();super.c()}$f(a,b){.01>a&&(a=.01);this.ac.gain.value=a;this.$b.gain.value=Math.pow(1/a,.6)*b}gf(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.mg(g,a,b);this.Qc[32768+d]=g;this.Qc[32768-d-1]=-g}}mg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.Dg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.ie=class extends f{constructor(a,b,d,g,n,q){super(a);this.R="compressor";this.g=[b,d,g,n,q];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=n;this.h.release.value=q}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.he=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Pd=new Float32Array(this.h.frequencyBinCount);this.ae=new Uint8Array(b);this.Zd=this.Na=0;this.i.Re(this)}c(){this.i.Tf(this);this.h.disconnect();super.c()}Ga(){this.h.getFloatFrequencyData(this.Pd);this.h.getByteTimeDomainData(this.ae);const a=this.h.fftSize;let b=this.Na=0;for(var d=0;d<a;++d){let g=(this.ae[d]-128)/128;0>g&&(g=-g);
this.Na<g&&(this.Na=g);b+=g*g}d=self.da.He;this.Na=d(this.Na);this.Zd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Be(){return{tag:this.Y,index:this.Rd,peak:this.Na,rms:this.Zd,binCount:this.h.frequencyBinCount,freqBins:this.Pd}}}}"use strict";
async function aa(f){if(!f.Ba)try{f.Ba=await navigator.wakeLock.request("screen"),f.Ba.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");f.Ba=null;v(f,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),v(f,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),v(f,"wake-lock-error")}}
function Z(){var f=document.body;const a=f.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");f=getComputedStyle(f);f=[f.getPropertyValue("--temp-sai-top"),f.getPropertyValue("--temp-sai-right"),f.getPropertyValue("--temp-sai-bottom"),f.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return f}
self.fa.Da(class extends self.sa{constructor(f){super(f,"platform-info");K(this,[["get-initial-state",()=>this.Fc()],["request-wake-lock",()=>aa(this)],["release-wake-lock",()=>{this.Ba&&(this.Ba.release(),this.Ba=null)}]]);window.addEventListener("resize",()=>{v(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Z()})});this.Ba=null}Fc(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Z(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";function ba(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>v(f,"sw-message",a.data))}
function ca(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.fa.Da(class extends self.sa{constructor(f){super(f,"browser");this.s="";K(this,[["get-initial-state",a=>this.Fc(a)],["ready-for-sw-messages",()=>ba(this)],["alert",a=>this.Cc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ic(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ca(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===
b){b=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Sg||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.s||"macos-wkwebview"===this.s)self.fa.Kb(!0),
this.A.Mc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",
()=>{"windows-webview2"===this.s||"macos-wkwebview"===this.s?(self.fa.Kb(!1),this.A.Mc({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{v(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{v(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{v(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{v(this,"backbutton")})}Fc(f){this.s=f.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}Cc(f){alert(f.message)}Ic(f){f=f.isFocus;if("nwjs"===this.s){const a="nwjs"===this.s?nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});
